version: 2.1


jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
           RAILS_ENV: test
           RACK_ENV: test
           BUNDLE_PATH: vendor/bundle
           BUNDLE_JOBS: 4
           BUNDLE_RETRY: 3
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-cache-v4-{{ checksum "Gemfile.lock" }}
            - bundler-cache-v4-
      - run:
          name: Install Ruby Dependencies
          command: bundle install
          
      - save_cache:
          key: bundler-cache-v4-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - ~/.bundle
      - run:
          name: Run Tests
          command: bin/rails test

workflows:
  version: 2
  test:
    jobs:
      - test      
