version: 2.1


jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.2-stretch-browsers-legacy
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: gem install bundler && bundle install
          
      - run:
          name: npm install
          command: npm install
          
      - run:
          name: Run Tests
          command: rails test

workflows:
  version: 2
  test:
    jobs:
      - test      
