version: 2.1


jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.2-stretch-browsers-legacy
        environment:
           NODE_ENV: test
           RAILS_ENV: test
           RACK_ENV: test
           BUNDLE_PATH: vendor/bundle
           BUNDLE_JOBS: 4
           BUNDLE_RETRY: 3
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: gem install bundler && bundle install
      - run:
          name: install system deps
          command: script/node_install.sh
      - run:
          name: npm install
          command: npm install
          
      - run:
          name: Run Tests
          command: rails test

workflows:
  version: 2
  test:
    jobs:
      - test      
