version: 2.1


jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.2-stretch-browsers-legacy
    steps:
      - checkout
      - run:
          name: echoing
          command: ruby -v 

workflows:
  version: 2
  test:
    jobs:
      - test      
